version: '3.8'

services:
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - data

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - data

volumes:
  redis-data:
  postgres-data:
  mongo-data:

networks:
  data:
